# Generated by Django 4.1.7 on 2023-03-10 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quarter_text", models.CharField(max_length=20)),
                (
                    "quarter_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            3,
                            10,
                            19,
                            47,
                            35,
                            353753,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "quarter_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            3,
                            10,
                            19,
                            47,
                            35,
                            353771,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_text", models.CharField(max_length=200)),
            ],
        ),
    ]
