# Generated by Django 4.1.7 on 2023-03-10 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generateReport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quarter",
            name="quarter_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 10, 19, 55, 32, 70243, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="quarter_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 10, 19, 55, 32, 70226, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
