# Generated by Django 4.1.7 on 2023-03-11 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generateReport", "0006_alter_quarter_quarter_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quarter",
            name="quarter_end",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 11, 14, 30, 56, 653070, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="quarter_start",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 11, 14, 30, 56, 653052, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
